### ISSUE TITLE
SPI examples fail with OVR induced panic

### ISSUE THREAD

**Issue by GregWoods** [smart-leds-rs/smart-leds-samples#5]
Using the spi samples I am able to get my strip of 7 neopixels to change to a set of fixed colors.
I adapted the ```stm32f0_ws2812_spi_slider.rs``` example to run on an stm32f411 "black pill" board, which was fairly easy (only a couple of days of studying the reference manual and hal for a noob to figure out!)

However, in all the variations code I've run, I cannot get more than one ```ws.write``` to occur. If I have code in a loop for animating the neopixels, nothing happens. I have checked the oscilloscope, and can confirm only one burst of data occurs.

To try to find out what is going on, I swapped out

```rust
        ws.write(data.iter().cloned()).unwrap();
```

for...

```rust
        let mut error_count = 0;
        loop {
            let result = ws.write(data.iter().cloned()); 
            if result.is_ok() || error_count > 100 {
                break;
            } else {
                error_count += 1;
            }
            //we don't currently check what type of error it is. We should!
            //hprintln!("ws2812 write error!").unwrap();  //superslow
        }
        if error_count > 0 {
            hprintln!("Error Count: {}", error_count).unwrap();
        }
```
Yes, I'm sure this is hideous, non-idiomatic way of doing things, but it show that ```ws.write`` returns an error, and some debugging shows it is an *OVR* overrun error.

From the stm32f4 reference manual I was unclear whether overruns can happen on write. My impression was that OVR was only for reading spi data.

My suspicion is that there is an underlying bug in ws2812-spi. but I wanted to raise it here first, to sanity check my findings.

I am happy to provide more info, and help out in any way I can.

**Comment by david-sawatzke** [comment]
This isn't quite a bug, but an unfortunate combination of various factors.

- `embedded-hal` only defines what happens if you `write` then `read` (successfully)
- This breaks up the data stream. That usually isn't an issue, but breaks the ws2812 timings, since the spi peripheral is (ab)used for bitbanging with proper timing.
- Some (most) hals don't clear the rx fifo when only writing, which leads to overruns when it's full (and they check for these errors, even when writing https://github.com/stm32-rs/stm32f4xx-hal/blob/f46baa8a57370e7b5ad956a33f8613d5bcb408a7/src/spi.rs#L1037)
- To work around this, ws2812-spi uses a non-blocking read (https://github.com/smart-leds-rs/ws2812-spi-rs/blob/fac281eb57b5f72c48e368682645e3b0bd5b4b83/src/lib.rs#L104). Most 
MCUs have an rx fifo thats one larger than the tx one, so this usually works.

This didn't lead to any issues (until now), but unfortunately the stm32f411 only has a 1-byte fifo for both rx and tx, which results in overruns.

I don't see any ways to improve this situation in general.

In your case, I can see two approaches:
- Try if making `read` blocking still results in a working output stream, since the gaps should be pretty small on the stm32f411
- Implement your own write-only spi driver, that uses the `transmit-only` mode of the spi peripheral.
  (Or some unsafe hacking around, bypassing the HAL only for the `FullDuplex` impl, but still leaving the initialization intact)
- Replace ws2812-spi with something else

**Comment by GregWoods** [comment]
Thanks for the comprehensive reply. You've filled in a lot of blanks in my knowledge.

I did get ws2812-spi working on the stm32f411, but with a terrible hack.

I forked stm32f4xx-hal, and in the spi module I added a line of code to ```send()```, which reads ```DR``` just before the existing code reads ```SR```. As stated in the Reference Manual, this is the way to clear OVR. It works for my use case, but I assume that by doing this I've crippled FullDuplex use of the spi peripheral!

I have yet to investigate your proposed options. The first one sounds like it could work in the short term, and is less hacky than my "solution"

I like the second option a lot, although I'd like it a lot more if someone else implemented the transmit only mode. It does look like the HAL is deficient in several areas when it comes to SPI. I may have a stab at it in the future.

As to replacing ws2912-spi. I don't see a lot of other options out there. Even switching hardware to the APA102 isn't going to help, as it still depends on SPI.

Anyway, you've certainly provided enough background for me to know it isn't a bug in the examples... and probably not really a bug in the ws2812-spi library.

Thanks for your help.
